### ISSUE TITLE
Special Price Configurable product issue

### ISSUE THREAD

**Issue by soloma88** [NVision-Commerce-Solutions/module-customer-price#12]
![image](https://github.com/NVision-Commerce-Solutions/module-customer-price/assets/1780242/01552681-950b-4f8e-a4c2-7c3d47c75d76)

Special price is showing for this product even if Special Price is off

**Comment by ldrooij** [comment]
This is not only an issue for configurable products. When there is no special price in BC, but a special price is set in Magento the  Magento special price is still use. See permalink below. I think it should return `null` instead of `$result`.

https://github.com/NVision-Commerce-Solutions/module-customer-price/blob/6f946f70af23db468116b695ebcca76e8c96aeac/Plugin/ProductPrice.php#L79

**Comment by soloma88** [comment]
Fixed
